import { caseProp, Person } from "./interfaces";

export const PEOPLE: Person[] = [
  {
    id: "1",
    name: "Karen Castillo",
    address: "Paradise Regained Hostel, Kumasi",
    avatarColor: "#FF6B6B",
    markerColor: "#FF6B6B",
    latitude: 6.675155,
    longitude: -1.571569,
    urgency: "critical",
    description:
      "Victim is experiencing severe breathing difficulties and chest tightness. Needs immediate oxygen support and medical personnel on site.",
    images: [
      "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=400&q=80",
    ],
    requesterDesc:
      "20-year old female student. Known to be asthmatic and highly sensitive to dust.",
    knownHealthProblems: ["Chronic Asthma", "Penicillin Allergy"],
  },
  {
    id: "2",
    name: "Alex Tan",
    address: "Old Library Road, KNUST",
    avatarColor: "#4ECDC4",
    markerColor: "#4ECDC4",
    latitude: 6.671234,
    longitude: -1.562145,
    urgency: "high",
    description:
      "Reported a head injury after slipping on a wet pathway near the central library. Conscious but bleeding slightly from the forehead.",
    images: [
      "https://images.unsplash.com/photo-1579684389782-64d84b5e905d?auto=format&fit=crop&w=400&q=80",
    ],
    requesterDesc: "22-year old male. Chemistry major. Alert and responsive.",
    knownHealthProblems: ["None"],
  },
  {
    id: "3",
    name: "Maria Santos",
    address: "J.A. Kuffour Avenue, KNUST",
    avatarColor: "#A78BFA",
    markerColor: "#A78BFA",
    latitude: 6.674512,
    longitude: -1.566789,
    urgency: "medium",
    description:
      "Suspicious individual spotted loitering around the hostel entrance for over two hours. Resident requests security patrol check.",
    images: [
      "https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=400&q=80",
    ],
    requesterDesc: "19-year old female resident of J.A. Kuffour Avenue.",
    knownHealthProblems: ["None"],
  },
  {
    id: "4",
    name: "David Mensah",
    address: "Georgia State Hostel, Kumasi",
    avatarColor: "#F59E0B",
    markerColor: "#F59E0B",
    latitude: 6.685123,
    longitude: -1.572145,
    urgency: "medium",
    description:
      "Power surge in the main distribution panel causing smoke and sparks. Campus electrician required to avoid fire risk.",
    images: [
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=400&q=80",
    ],
    requesterDesc: "Hostel Warden at Georgia State.",
    knownHealthProblems: ["Diabetes Type 2"],
  },
  {
    id: "5",
    name: "Elena Boateng",
    address: "Asokwa Mall, Kumasi",
    avatarColor: "#EC4899",
    markerColor: "#EC4899",
    latitude: 6.652134,
    longitude: -1.583124,
    urgency: "critical",
    description:
      "Severe allergic reaction (anaphylaxis) from accidental peanut consumption. Epipen has been administered but victim requires transport.",
    images: [
      "https://images.unsplash.com/photo-1628863012283-709ffb77df0c?auto=format&fit=crop&w=400&q=80",
    ],
    requesterDesc:
      "21-year old female student. Currently monitored by a friend.",
    knownHealthProblems: ["Severe Peanut Allergy", "Lactose Intolerance"],
  },
];

export const emergencyAlerts: caseProp[] = [
  {
    id: "1",
    title: "Severe breathing difficulties",
    description:
      "Victim is experiencing severe breathing difficulties and chest tightness. Needs immediate oxygen support.",
    location: "Paradise Regained Hostel, Kumasi",
    distance: 200,
    time: 120,
    responseTime: 180,
    severity: "Critical",
    responders: 4,
    isResolved: false,
    action: "Respond",
    creatorID: "user_001",
    falseAlarm: false,
  },
  {
    id: "2",
    title: "Head injury reported",
    description:
      "Reported a head injury after slipping on a wet pathway near the central library. Conscious but bleeding.",
    location: "Old Library Road, KNUST",
    distance: 400,
    time: 480,
    responseTime: 300,
    severity: "Moderate",
    responders: 2,
    isResolved: false,
    action: "Respond",
    creatorID: "user_002",
    falseAlarm: false,
  },
  {
    id: "3",
    title: "Suspicious individual loitering",
    description:
      "Suspicious individual spotted loitering around the hostel entrance for over two hours.",
    location: "J.A. Kuffour Avenue, KNUST",
    distance: 600,
    time: 900,
    responseTime: 420,
    severity: "Low",
    responders: 1,
    isResolved: false,
    action: "Respond",
    creatorID: "user_003",
    falseAlarm: false,
  },
  {
    id: "4",
    title: "Electrical fire hazard",
    description:
      "Power surge in the main distribution panel causing smoke and sparks.",
    location: "Georgia State Hostel, Kumasi",
    distance: 750,
    time: 1200,
    responseTime: 240,
    severity: "Moderate",
    responders: 3,
    isResolved: false,
    action: "Respond",
    creatorID: "user_004",
    falseAlarm: false,
  },
  {
    id: "5",
    title: "Severe allergic reaction",
    description:
      "Severe allergic reaction (anaphylaxis) from accidental peanut consumption. Epipen administered.",
    location: "Asokwa Mall, Kumasi",
    distance: 1200,
    time: 1500,
    responseTime: 480,
    severity: "Critical",
    responders: 5,
    isResolved: false,
    action: "Respond",
    creatorID: "user_005",
    falseAlarm: false,
  },
  {
    id: "6",
    title: "Fire alarm resolved",
    description: "Smoke cleared and sensor reset",
    location: "Engineering Lab, KNUST",
    distance: 750,
    time: 7200,
    responseTime: 240,
    severity: "Resolved",
    responders: 6,
    isResolved: true,
    action: "",
    creatorID: "sensor_lab_01",
    falseAlarm: false,
  },
  {
    id: "7",
    title: "Medical assistance completed",
    description: "Patient safely transported to hospital",
    location: "Paradise Regained Hostel",
    distance: 50,
    time: 14400,
    responseTime: 180,
    severity: "Resolved",
    responders: 2,
    isResolved: true,
    action: "",
    creatorID: "user_008",
    falseAlarm: false,
  },
];
