import { Person } from "./interfaces";

export const PEOPLE: Person[] = [
  {
    id: "1",
    name: "Karen Castillo",
    address: "Paradise Regained Hostel",
    avatarColor: "#FF6B6B",
    markerColor: "#FF6B6B",
    latitude: 6.675154753941343,
    longitude: -1.5715685289849886,

    urgency: "critical",
  },
  {
    id: "2",
    name: "Alex Tan",
    address: "Cantonments Road, East Legon",
    avatarColor: "#4ECDC4",
    markerColor: "#4ECDC4",
    latitude: 6.6698627266087405,
    longitude: -1.5611214902241275,
    urgency: "high",
  },
  {
    id: "3",
    name: "Maria Santos",
    address: "Labadi Beach Rd, La",
    avatarColor: "#A78BFA",
    markerColor: "#A78BFA",
    latitude: 5.593,
    longitude: -0.175,
    urgency: "medium",
  },
];

export const emergencyAlerts = [
  {
    id: "1",
    title: "Medical emergency",
    description: "Student collapsed during lecture",
    location: "Science Block",
    distance: "200m",
    time: "2 min ago",
    severity: "Critical",
    isResolved: false,
    color: "#FF5C5C",
    action: "Respond",
  },
  {
    id: "2",
    title: "Theft reported",
    description: "Phone snatched from student",
    location: "Library Car Park",
    distance: "400m",
    time: "8 min ago",
    severity: "Moderate",
    isResolved: false,
    color: "#F4B63D",
    action: "Details",
  },
  {
    id: "3",
    title: "Suspicious activity",
    description: "Unknown individual loitering near hostel entrance",
    location: "Hall C Gate",
    distance: "600m",
    time: "15 min ago",
    severity: "Low",
    isResolved: false,
    color: "#7AC943",
    action: "Details",
  },
  {
    id: "4",
    title: "Fire alarm",
    description: "Smoke detected in laboratory",
    location: "Engineering Lab",
    distance: "750m",
    time: "20 min ago",
    severity: "Critical",
    isResolved: false,
    color: "#FF5C5C",
    action: "Respond",
  },
  {
    id: "5",
    title: "Road accident",
    description: "Motorbike collision reported",
    location: "Main Entrance",
    distance: "1.2 km",
    time: "25 min ago",
    severity: "Critical",
    isResolved: false,
    color: "#FF5C5C",
    action: "Respond",
  },
  {
    id: "6",
    title: "Power outage",
    description: "Electricity outage affecting hostels",
    location: "Republic Hall",
    distance: "900m",
    time: "30 min ago",
    severity: "Moderate",
    isResolved: false,
    color: "#F4B63D",
    action: "Details",
  },
  {
    id: "7",
    title: "Flood warning",
    description: "Water level rising after heavy rain",
    location: "Commercial Area",
    distance: "1.8 km",
    time: "35 min ago",
    severity: "Moderate",
    isResolved: false,
    color: "#F4B63D",
    action: "View",
  },
  {
    id: "8",
    title: "Gas leak",
    description: "Possible LPG leak detected",
    location: "Food Court",
    distance: "500m",
    time: "40 min ago",
    severity: "Critical",
    isResolved: false,
    color: "#FF5C5C",
    action: "Respond",
  },
  {
    id: "9",
    title: "Lost child",
    description: "Child separated from guardian",
    location: "Sports Complex",
    distance: "850m",
    time: "45 min ago",
    severity: "Low",
    isResolved: false,
    color: "#7AC943",
    action: "Help",
  },
  {
    id: "10",
    title: "Traffic congestion",
    description: "Heavy traffic due to stalled vehicle",
    location: "Campus Roundabout",
    distance: "1.1 km",
    time: "50 min ago",
    severity: "Low",
    isResolved: false,
    color: "#7AC943",
    action: "View",
  },
  {
    id: "11",
    title: "Fire alarm (False alarm)",
    description: "Alarm triggered accidentally",
    location: "Admin Block",
    distance: "",
    time: "1 hr ago",
    severity: "Resolved",
    isResolved: true,
    color: "#7F8C6B",
    action: "",
  },
  {
    id: "12",
    title: "Medical assistance completed",
    description: "Patient safely transported to hospital",
    location: "Hostel 7",
    distance: "",
    time: "2 hrs ago",
    severity: "Resolved",
    isResolved: true,
    color: "#7F8C6B",
    action: "",
  },
];
