import { caseProp, Person } from "./interfaces";

export const PEOPLE: Person[] = [
  {
    id: "1",
    name: "Karen Castillo",
    address: "Paradise Regained Hostel",
    avatarColor: "#FF6B6B",
    markerColor: "#FF6B6B",
    latitude: 6.675154753941343,
    longitude: -1.5715685289849886,

    urgency: "critical",
  },
  {
    id: "2",
    name: "Alex Tan",
    address: "Cantonments Road, East Legon",
    avatarColor: "#4ECDC4",
    markerColor: "#4ECDC4",
    latitude: 6.6698627266087405,
    longitude: -1.5611214902241275,
    urgency: "high",
  },
  {
    id: "3",
    name: "Maria Santos",
    address: "Labadi Beach Rd, La",
    avatarColor: "#A78BFA",
    markerColor: "#A78BFA",
    latitude: 5.593,
    longitude: -0.175,
    urgency: "medium",
  },
];

export const emergencyAlerts: caseProp[] = [
  {
    id: 1,
    title: "Medical emergency",
    description: "Student collapsed during lecture",
    location: "Science Block",
    distance: 200,
    time: 120,
    responseTime: 180,
    severity: "Critical",
    responders: 4,
    isResolved: false,
    action: "Respond",
    creatorID: "user_001",
    falseAlarm: false,
  },
  {
    id: 2,
    title: "Theft reported",
    description: "Phone snatched from student",
    location: "Library Car Park",
    distance: 400,
    time: 480,
    responseTime: 300,
    severity: "Moderate",
    responders: 2,
    isResolved: false,
    action: "Details",
    creatorID: "user_014",
    falseAlarm: false,
  },
  {
    id: 3,
    title: "Suspicious activity",
    description: "Unknown individual loitering near hostel entrance",
    location: "Hall C Gate",
    distance: 600,
    time: 900,
    responseTime: 420,
    severity: "Low",
    responders: 1,
    isResolved: false,
    action: "Details",
    creatorID: "user_006",
    falseAlarm: false,
  },
  {
    id: 4,
    title: "Fire alarm",
    description: "Smoke detected in laboratory",
    location: "Engineering Lab",
    distance: 750,
    time: 1200,
    responseTime: 240,
    severity: "Critical",
    responders: 6,
    isResolved: false,
    action: "Respond",
    creatorID: "sensor_lab_01",
    falseAlarm: false,
  },
  {
    id: 5,
    title: "Road accident",
    description: "Motorbike collision reported",
    location: "Main Entrance",
    distance: 1200,
    time: 1500,
    responseTime: 480,
    severity: "Critical",
    responders: 5,
    isResolved: false,
    action: "Respond",
    creatorID: "user_023",
    falseAlarm: false,
  },
  {
    id: 6,
    title: "Power outage",
    description: "Electricity outage affecting hostels",
    location: "Republic Hall",
    distance: 900,
    time: 1800,
    responseTime: 360,
    severity: "Moderate",
    responders: 2,
    isResolved: false,
    action: "Details",
    creatorID: "maintenance_01",
    falseAlarm: false,
  },
  {
    id: 7,
    title: "Flood warning",
    description: "Water level rising after heavy rain",
    location: "Commercial Area",
    distance: 1800,
    time: 2100,
    responseTime: 600,
    severity: "Moderate",
    responders: 3,
    isResolved: false,
    action: "View",
    creatorID: "weather_service",
    falseAlarm: false,
  },
  {
    id: 8,
    title: "Gas leak",
    description: "Possible LPG leak detected",
    location: "Food Court",
    distance: 500,
    time: 2400,
    responseTime: 300,
    severity: "Critical",
    responders: 4,
    isResolved: false,
    action: "Respond",
    creatorID: "sensor_gas_03",
    falseAlarm: false,
  },
  {
    id: 9,
    title: "Lost child",
    description: "Child separated from guardian",
    location: "Sports Complex",
    distance: 850,
    time: 2700,
    responseTime: 420,
    severity: "Low",
    responders: 2,
    isResolved: false,
    action: "Help",
    creatorID: "user_031",
    falseAlarm: false,
  },
  {
    id: 10,
    title: "Traffic congestion",
    description: "Heavy traffic due to stalled vehicle",
    location: "Campus Roundabout",
    distance: 1100,
    time: 3000,
    responseTime: 540,
    severity: "Low",
    responders: 1,
    isResolved: false,
    action: "View",
    creatorID: "traffic_cam_02",
    falseAlarm: false,
  },
  {
    id: 11,
    title: "Fire alarm",
    description: "Alarm triggered accidentally",
    location: "Admin Block",
    distance: 900,
    time: 3600,
    responseTime: 240,
    severity: "Resolved",
    responders: 3,
    isResolved: true,
    action: "",
    creatorID: "sensor_admin_01",
    falseAlarm: true,
  },
  {
    id: 12,
    title: "Medical assistance completed",
    description: "Patient safely transported to hospital",
    location: "Hostel 7",
    distance: 50,
    time: 7200,
    responseTime: 180,
    severity: "Resolved",
    responders: 2,
    isResolved: true,
    action: "",
    creatorID: "user_008",
    falseAlarm: false,
  },
];
